class SeedEventTaskTimings < ActiveRecord::Migration[5.2]
  def up
    tasks = [
      ["Event Admin",             2, "Complex"],
      ["Send FD's",               2, "Complex"],
      ["Confirm Final Team",      4, "Complex"],
      ["Logistics Confirm/Cx",    5, "Complex"],
      ["Clear Replies",           5, "Complex"],
      ["Send Email/Call backs",   8, "Complex"],
      ["Onsite Leadership",      10, "Complex"],
      ["Planning Meeting",       11, "Complex"],
      ["Client Contact",         12, "Complex"],
      ["Marketing",              15, "Complex"],
      ["Assess Team",            15, "Complex"],
      ["Key Players",            17, "Complex"],
      ["Send Reserve/Booked",    19, "Complex"],
      ["Assess Numbers",         22, "Complex"],
      ["Clear Replies",          22, "Complex"],
      ["Send Reserve/Booked",    22, "Complex"],
      ["Cull Non-Responses",     22, "Complex"],
      ["Send Beepro",            25, "Complex"],
      ["Prep Beepro",            26, "Complex"],
      ["Vet Requests",           29, "Complex"],
      ["Planning Meeting",       30, "Complex"],
      ["Key Players",            31, "Complex"],
      ["Vet Requests",           36, "Complex"],
      ["Marketing",              43, "Complex"],
      ["Key Players",            45, "Complex"],
      ["Vet Requests",           50, "Complex"],
      ["Assess Numbers",         56, "Complex"],
      ["Vet Requests",           63, "Complex"],
      ["Vet Requests",           70, "Complex"],
      ["Clear Replies",          74, "Complex"],
      ["Logistics Bookings",     79, "Complex"],
      ["Marketing",              80, "Complex"],
      ["Open on Website",        81, "Complex"],
      ["Planning Meeting",       106, "Complex"],

      ["Event Admin",             2, "Large"],
      ["Send FD's",               2, "Large"],
      ["Confirm Final Team",      4, "Large"],
      ["Logistics Confirm/Cx",    5, "Large"],
      ["Clear Replies",           5, "Large"],
      ["Send Email/Call backs",   8, "Large"],
      ["Onsite Leadership",      10, "Large"],
      ["Client Contact",         12, "Large"],
      ["Marketing",              15, "Large"],
      ["Assess Team",            15, "Large"],
      ["Assess Numbers",         15, "Large"],
      ["Send Reserve/Booked",    19, "Large"],
      ["Assess Numbers",         22, "Large"],
      ["Clear Replies",          22, "Large"],
      ["Send Reserve/Booked",    22, "Large"],
      ["Cull Non-Responses",     22, "Large"],
      ["Send Beepro",            25, "Large"],
      ["Prep Beepro",            26, "Large"],
      ["Vet Requests",           29, "Large"],
      ["Vet Requests",           36, "Large"],
      ["Marketing",              43, "Large"],
      ["Vet Requests",           50, "Large"],
      ["Assess Numbers",         56, "Large"],
      ["Vet Requests",           63, "Large"],
      ["Vet Requests",           70, "Large"],
      ["Clear Replies",          74, "Large"],
      ["Logistics Bookings",     79, "Large"],
      ["Marketing",              80, "Large"],
      ["Open on Website",        81, "Large"],
      ["Planning Meeting",       106, "Large"],

      ["Event Admin",              2, "Medium+"],
      ["Send FD's",                2, "Medium+"],
      ["Confirm Final Team",       3, "Medium+"],
      ["Clear Replies",            4, "Medium+"],
      ["Send Email/Call backs",    5, "Medium+"],
      ["Logistics Confirm/Cx",     5, "Medium+"],
      ["Client Contact",           5, "Medium+"],
      ["Onsite Leadership",       10, "Medium+"],
      ["Assess Team",             11, "Medium+"],
      ["Clear Replies",           15, "Medium+"],
      ["Send Reserve/Booked",     15, "Medium+"],
      ["Send Beepro",             18, "Medium+"],
      ["Prep Beepro",             19, "Medium+"],
      ["Vet Requests",            22, "Medium+"],
      ["Vet Requests",            29, "Medium+"],
      ["Marketing",               29, "Medium+"],
      ["Vet Requests",            36, "Medium+"],
      ["Open on Website",         40, "Medium+"],
      ["Planning Meeting",        67, "Medium+"],
      
      ["Event Admin",              2, "1 Day Simple"],
      ["Send FD's",                2, "1 Day Simple"],
      ["Confirm Final Team",       3, "1 Day Simple"],
      ["Clear Replies",            4, "1 Day Simple"],
      ["Send Email/Call backs",    5, "1 Day Simple"],
      ["Logistics Confirm/Cx",     5, "1 Day Simple"],
      ["Client Contact",           5, "1 Day Simple"],
      ["Cull Non-Responses",      15, "1 Day Simple"],
      ["Clear Replies",           15, "1 Day Simple"],
      ["Send Booked/Shift Offer", 19, "1 Day Simple"],
      ["Vet Requests",            22, "1 Day Simple"],
      ["Vet Requests",            29, "1 Day Simple"],
      ["Marketing",               29, "1 Day Simple"],
      ["Vet Requests",            36, "1 Day Simple"],
      ["Open on Website",         40, "1 Day Simple"],
      ["Planning Meeting",        60, "1 Day Simple"],

      ["Event Admin",             2, "Small 1-10"],
      ["Send FD's",               3, "Small 1-10"],
      ["Confirm Final Team",      4, "Small 1-10"],
      ["Send Email/Call backs",   5, "Small 1-10"],
      ["Client Contact",          5, "Small 1-10"],
      ["Clear Replies",          15, "Small 1-10"],
      ["Send Reserve/Booked",    15, "Small 1-10"],
      ["Open on Website",        19, "Small 1-10"],
    ]
   
    tasks.each do |task|
      EventTaskTiming.create!(template: EventTaskTemplate.find_by_task(task[0]), days: task[1], size: EventSize.find_by_name(task[2]), type: 'BEFORE_EVENT_START')
    end
  end
  def down
    EventTaskTiming.destroy_all
  end
end
